#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      namespace: api
      labels:
        app: trips
    spec:
      containers:
        - image: "registryscg1665.azurecr.io/tripinsights/trips:1.0"
          name: trips
          env:
          - name: SQL_USER
            value: "sqladminsCg1665"
          - name: SQL_SERVER
            value: "sqlserverscg1665.database.windows.net"
          - name: SQL_DBNAME
            value: "mydrivingDB"
          - name: WEB_PORT
            value: "80"
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripviewer-keyvault"
---
#service
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  selector:
    app: trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
